extends:
    - oclif
    - oclif-typescript
rules: {
  'max-params': ['warn', 6],
  'unicorn/prefer-type-error': 'off',
  'import/no-extraneous-dependencies': 'off',
  'import/extensions': 'off',
  'no-console': 'off',
  'max-len': 'off',
  'camelcase': 'off',
  'class-methods-use-this': 'off',
  'prefer-destructuring': 'off',
  'semi': [ 'error', 'never' ],
  '@typescript-eslint/ban-ts-ignore': 'off',
  '@typescript-eslint/no-this-alias': 'off',
  'no-warning-comments': 'off',
  'unicorn/no-abusive-eslint-disable': 'off'
}
